#%RAML 1.0 NamedExample 
errorCode: "NOT_FOUND"
errorMessage: "The server has not found anything matching the Requested URI"
transactionId: "11111111-1111-1111-1111-111111111111"
timeStamp: "2022-09-01T12:06:42.392-05:00"
