#%RAML 1.0 NamedExample
errorCode: "NOT_ACCEPTABLE"
errorMessage: "The client requested a response type which cannot be obtained from the requested resource. Check the requested endpoint response capabilities and compare them with your client Accept header."
transactionId: "11111111-1111-1111-1111-111111111111"
timeStamp: "2022-09-01T12:06:42.392-05:00"
