#%RAML 1.0 DataType
  properties:
    correlation-id: 
      type: string
      required: true
    code: 
      type: string
      required: false
    message:
      type: string
      required: false 