#%RAML 1.0 Trait
headers:
  client_id: 
    description: client id
    type: string
    pattern: ^[a-zA-Z0-9]{32}$
  client_secret:
    description: client secret
    type: string
    pattern: ^[a-zA-Z0-9]{32}$
