#%RAML 1.0 Trait
queryParameters:
  next: 
    type: string
    required: false
    description: Url to next page, which is returned in the previous response
    example: "https://sample.com/entityName/token/1234567890123456"