#%RAML 1.0 Trait
headers:
  x-source-system:
    type: string
    description: A unique identification string for the source system. This could be a system name or hostname where a system is hosted on multiple hosts.
    required: false
    example: "Salesforce Experience API"