#%RAML 1.0 Trait
    responses:
      201:
        body:
          application/json:
            type: !include ../../data-types/201-response-batch-type.raml
            example: !include ../../examples/success/201-batch-example.raml