#%RAML 1.0 Trait
    responses:
      404:
        body:
          application/json:
            type: !include ../../data-types/standard-response-type.raml
            example: !include ../../examples/fault/404-example.raml