#%RAML 1.0 Trait
    responses:
      500:
        body:
          application/json:
            type: !include ../../data-types/standard-response-type.raml
            example: !include ../../examples/fault/500-example.raml